spring: 
  h2: 
    console: 
      enabled: true
  jpa:
      show-sql: true # 실행 되는 SQL문을 보여 줄지 설정
      properties:  
        hibernate.format_sql: true # 형식화된 sql 문을 보여준다. Beautifier 기능이라고 생각하면 된다
        hibernsate.enable_lazy_load_no_trans: true #Lazy Load 를 적용하기 위한 설정